### ISSUE TITLE
in my project the V is not defined

### ISSUE THREAD

**Issue by yertYang** [JoseGoncalves/vue-jointjs#1]
**V**('rect')

paper.on('element:pointermove', function (view, evt, x, y) {
      const data = evt.data
      if (data.ghost) {
        data.ghost.attr({
          x: x - data.dx,
          y: y - data.dy
        })
      } else {
        const bbox = view.model.getBBox()
        const ghost = **V**('rect')
        ghost.attr(bbox)
        ghost.attr({
          fill: 'transparent',
          stroke: '#5755a1',
          'stroke-dasharray': '4,4',
          'stroke-width': 2
        })
        ghost.appendTo(this.viewport)
        evt.data.ghost = ghost
        evt.data.dx = x - bbox.x
        evt.data.dy = y - bbox.y
      }
    })

**Comment by JoseGoncalves** [comment]
My demo app does not make use of the V library shipped inside JointJS, so I did not import it.
I think your best option would be to import that library in a Vue plugin.
Check this article for more info: [Use Any JavaScript Library With Vue.js](https://vuejsdevelopers.com/2017/04/22/vue-js-libraries-plugins/)

**Comment by yertYang** [comment]
my mistake sorry &thanks
