### ISSUE TITLE
Use of LinkTools

### ISSUE THREAD

**Issue by DSC-CSTS** [JoseGoncalves/vue-jointjs#2]
Hi @JoseGoncalves,

This is not really an issue but since I used your example in my own project I thought I should ask here.

Drawing shapes in my own project is not an issue (thanks to this example) but now I want to use the linkTools in my vue-project (to highlight connections). Therefore I changed the rappid.js to the following:
```
import "jointjs/dist/joint.core.css";

import { dia } from "jointjs/src/core.mjs";
import * as standard from "jointjs/src/shapes/standard.mjs";
import * as devs from "jointjs/src/shapes/devs.mjs";
import * as linkTools from "jointjs/src/linkTools/index.mjs";

export default {
  install: function(Vue) {
    let joint = { dia };
    joint.shapes = { standard, devs };
    joint.linkTools = { linkTools };
    Object.defineProperty(Vue.prototype, "$joint", { value: joint });
  }
};
```
Then I call the following in my component:
`var segmentsTool = new this.$joint.linkTools.Segments();`
This doesn't work because I get the error: **this.$joint.linkTools.Segments is not a constructor**

Is it possible to extend your example with linkTools or do you have any idea how to solve this? (I Googled a lot already but didn't find an answer on this).

I hope you can help me out.

Regards,
Dirk

**Comment by JoseGoncalves** [comment]
Hi @DSC-CSTS 

I don't see anything wrong in the way you have done the import of `linkTools`, but I tested, and it really doesn't work.
Try it in the following way, it works for me:

```javascript
import 'jointjs/dist/joint.core.css';

import { dia, linkTools } from 'jointjs/src/core.mjs';
import * as standard from 'jointjs/src/shapes/standard.mjs';
import * as devs from 'jointjs/src/shapes/devs.mjs';

export default {
	install: function (Vue) {
		let joint = { dia, linkTools };
		joint.shapes = { standard, devs };
		Object.defineProperty(Vue.prototype, '$joint', { value: joint });
	}
};

```

**Comment by DSC-CSTS** [comment]
Hi @JoseGoncalves,

Thanks for your quick response, and.... what you suggested also worked on my side!! 
Thanks a lot for your help!! This really saves me a lot of time!

Regards,
Dirk
